//TODO:リクエストの結果によってメッセージを表示する処理を追加すること
//$(".js_flash").removeClass("is_open");
//$(".js_flash").addClass("is_close");
//$(".js_flash").removeClass("is_close");
//$(".js_flash").addClass("is_open");
//$(".js_error").removeClass("is_open");
//$(".js_error").addClass("is_close");
//$(".js_error").removeClass("is_close");
//$(".js_error").addClass("is_open");
